[workspace]
resolver = "2"

members = [ "package_builder","feature_macro"]

[workspace.dependencies]
quote = "1.0.36"
rand = "0.8.5"
syn = { version = "2.0.60", features = ["full"] }

[patch.crates-io]
